### ISSUE TITLE
small imporovements height profile print

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#528] opened 2024-02-19 11:20 UTC
I would suggest to place the print button directly underneath the header as it realized in legend print. Now it is placed at the bottom. The generated html page is not scrollable (just in my case?) and in this case the button is missed by the user, when it is outside of the visible page extent.

And furthermore external layers are not printed in the map if they don't provide a specific style as the `STYLE` is named `undefined` and not `default`. I got this error here:
```
 <ServiceException code="StyleNotDefined">unsupported styles: undefined</ServiceException>
```

**Comment by manisandro** [comment] 2024-02-19 11:40
Thanks, the improvements to the legend print page are implemented in https://github.com/qgis/qwc2/commit/10b88bdbeedbbb3def714971659503ec347a4fa4.

Can you send me the full GetMap URL for which you get the error?

**Comment by manisandro** [comment] 2024-02-19 13:48
I cannot reproduce this with the latest qwc2 master. What version are you using? Is this a freshly set up map or a restored permalink?

**Comment by danceb** [comment] 2024-02-19 14:58
I've tested it with another external wms service which is not part of our mapproxy and it works as expected there. So it seems to be related with the mapproxy and how the style naming/requesting is handled there.

**Comment by danceb** [comment] 2024-02-19 15:15
mh, it seems I have no option in mapproxy to control this, as a mapproxy layer does not have different styles. So where does the style name in the GetMap-Request comes from if no style name is provided by the requested wms?

**Comment by manisandro** [comment] 2024-02-19 15:30
For external layers, this is here [1], which is then used here [2] and finally here [3] when building the print params. The `undefined` leaves me a bit perplexed, since throughout the fallback for undefined values is an empty string. Can you check where the `undefined` comes from by inspecting the values of style around [1], [2] and [3]?

[1] https://github.com/qgis/qwc2/blob/10b88bdbeedbbb3def714971659503ec347a4fa4/utils/ServiceLayerUtils.js#L209
[2] https://github.com/qgis/qwc2/blob/10b88bdbeedbbb3def714971659503ec347a4fa4/utils/LayerUtils.js#L172
[3] https://github.com/qgis/qwc2/blob/10b88bdbeedbbb3def714971659503ec347a4fa4/utils/LayerUtils.js#L795

**Comment by manisandro** [comment] 2024-02-21 10:17
We've just had a similar situation, and the cause was that in the manually defined background layer WMS params, there were N entries in LAYERS, and a STYLE param with just one entry. Perhaps this is the same problem here? STYLE needs to have the same number of (comma separated) entries as LAYERS.

**Comment by danceb** [comment] 2024-02-23 11:30
Results of some more testing:

The issue only occurs, if a wms as set as `"printLayer"` in the background layer config and this one is used for printing. I have tested it with different wms services (our owns and also externals) and its always `STYLES=undefined`.

It works, if the background layer itself is a wms and used for printing as well without an additional print layer config.

**Comment by manisandro** [comment] 2024-02-23 11:32
You mean `"printLayer": "wms:<url>#<layername>"?

**Comment by danceb** [comment] 2024-02-23 11:32
Yes, exactly. As there is only the possibility to set the layer name for printing and not a style name in the ressource string, maybe the issue somewhere here.

**Comment by manisandro** [comment] 2024-02-23 11:33
Ok thanks, I'll investigate

**Comment by manisandro** [comment] 2024-02-23 11:43
Ok found it, should be fixed in https://github.com/qgis/qwc2/commit/c4be3e974381384f67b2fe09e8dbe80c6acf4ef4

**Closed by manisandro** 2024-02-23 11:43 UTC
