### ISSUE TITLE
Routing plugin: Symbology of routes and reachability areas map viewer vs print/export

### ISSUE THREAD

**Issue by danceb** [qgis/qwc2-demo-app#558] opened 2024-06-14 07:02 UTC
I discovered, that the symbology of routes and reachability areas created with the routing plugin differs within the map view compared to the version which is printed/exported as image. As the color is hard coded with `rgb(10, 10, 255)` within the plugin, the style which is used for export is a different one (I don't get, where it comes from). Moreover the route itself is missing within the export (the way points are printed).

Routing:
![grafik](https://github.com/qgis/qwc2-demo-app/assets/30999402/03940903-6038-4983-826f-a504602e6d5d)
![grafik](https://github.com/qgis/qwc2-demo-app/assets/30999402/ed0c0607-d77e-4581-8f0b-033dbe3425f9)

Reachability:
![grafik](https://github.com/qgis/qwc2-demo-app/assets/30999402/98c1176a-7e0f-4416-b82b-b2ac36a3d19c)
![grafik](https://github.com/qgis/qwc2-demo-app/assets/30999402/e25bff58-ea67-4144-9c32-78bf66a1b645)

It would be nice to get the route printed aswell and furthermore the same symbology for the way points, routing lines and area polygons and used font family of the labels within the map and print/export.

**Comment by manisandro** [comment] 2024-06-17 14:25
The mismatching geometry style should be fixed by [1]. Regarding the markers, the problem is that the marker symbol is not available to the server resp QGIS Server currently does not appear to correctly handle references to images in the SLD symbology.

[1] https://github.com/qgis/qwc2/commit/682113a8966b5603de96fab335470e1d1974ba92

**Comment by danceb** [comment] 2024-06-17 21:22
Ok, I see. Thanks for the fix for the mismatching geometry styles! But is there a chance to consider the font family of the label in the map viewer aswell?

**Comment by manisandro** [comment] 2024-06-17 21:25
Not via request, the redlining request parameters do not allow you to specify the font family [1]. What could/should work is setting the default font family in the QGIS Server environment.

[1] https://docs.qgis.org/3.16/en/docs/server_manual/services.html#redlining

**Closed** 2024-07-17 09:40 UTC

**Comment by danceb** [comment] 2024-07-18 08:46
Just one thing: What do you think about another config parameter `extraRedliningParameters` for the redlining plugin? As within the MapLegend plugin [1] this could give the user the possibility to define standards for the `HIGHLIGHT` parameters of the QGIS Server which should then be considered in `GetMap` and `GetPrint` request.

[1] https://qwc-services.github.io/master/references/qwc2_plugins/#maplegend
[2] https://docs.qgis.org/3.34/en/docs/server_manual/services/wms.html#redlining

**Comment by manisandro** [comment] 2024-07-18 08:49
This would need to be specified in more detail, the highlight parameters are per feature, you cannot really define a global set of parameters to just append to the request.

**Comment by danceb** [comment] 2024-07-18 08:52
uh, I see, thanks for clarification.

**Comment by danceb** [comment] 2024-08-29 20:23
I just came across this again ...

Just for my understanding: Could you please clearify, why this is working with the routing labels and not the redlining labels?

The labels of the routing way points are using the same font family within the map view and in the result of GetMap requests of the MapExport plugin and GetPrint requests of the Print plugin:

map viewer:
![grafik](https://github.com/user-attachments/assets/f5b273d8-77fb-4356-bcc7-d2959715fa16)

map export:
![grafik](https://github.com/user-attachments/assets/57b21bc2-bff0-4102-be85-0f2cb33453b4)

So what font family is this and where does it come from?

With the redlining it looks like this:

map view:
![grafik](https://github.com/user-attachments/assets/79ac6c53-a277-404f-ac7b-9eb2a47bbbb8)

map export:
![grafik](https://github.com/user-attachments/assets/389f9c14-6030-4bcf-a4ac-a4352b6a2fce)
This is how it looks before with the routing labels, too. I think Dejavu font is used here.

as you mentioned, it has to be specified in more detail, as the font family (and other highlight parameters) could be defined per feature. But wouldn't it be a better way to specify something which is the same for alle features than nothing?

What I have in my mind: 
specify the parameter within the plugin config:
`highlight_labelfont: Arial`

do a search replace within the request, for instance at this position:
`HIGHLIGHT_LABELSTRING` -> `HIGHLIGHT_LABELFONT=<highlight_labelfont>&HIGHLIGHT_LABELSTRING`

For more than one feature maybe it's possible to count the `%3B` of `HIGHLIGHT_LABELSTRING` and adding respective `HIGHLIGHT_LABELFONT=<highlight_labelfont>%3B<highlight_labelfont>`.

Would this be an option?

Unfortunately I couldn't find an option to pass the default font family to QGIS Server via ENV, I think, this case isn't covered there ...
