### ISSUE TITLE
Each tile loaded is declared as a "previous web page"

### ISSUE THREAD

**Issue by haubourg** [qgis/qwc2-demo-app#148] opened 2019-06-12 07:03 UTC
Just checked on some recent demo here:

http://qgis4.qgis.org:8081/qwc2_demo/?bl=mapnik&st=&l=Hilfsorganisationen%2CBushaltestellen%2CAbfallwirtschaft%2CLinien%2CBeschriftung&t=qwc2_demo

Just opening the application already fills the "go-back pages" list of the browser, and I suppose we have one entry for each loaded tile. 
The ideal situation would be to exclude getmap requests from being seen as page navigation, but let some actions in this, like adding a layer, changing the transparency, of course changing theme... 

 
![image](https://user-images.githubusercontent.com/1629853/59330140-f4496080-8cf0-11e9-97f8-54d4a88d6aab.png)

**Comment by haubourg** [comment] 2019-06-12 07:04
ping @elemoine

**Comment by elemoine** [comment] 2019-06-13 05:37
@haubourg I don't think the issue is related to the tiles, it is related to the link (in the address bar) that is changed by QWC2 at application initialization time. That being said I agree with you that the current behaviour is not ideal and needs improvements.

**Comment by elemoine** [comment] 2019-06-13 05:54
To be more specific the problem is related to UrlParams.updateParams calling history.pushState on each call. There certainly is a better way, maybe by calling history.pushState in a task (setTimeout(0) callback) or  a microtask.

**Comment by elemoine** [comment] 2019-06-13 13:06
@haubourg see https://github.com/qgis/qwc2/pull/79. With this PR the current history entry is modified instead of creating a new history entry. This fixes the "many entries in the history after page load" issue you're seeing. But it does not address the "but let some actions in this, like adding a layer, changing the transparency, of course changing theme..." feature you are requesting, which could be done with a separate PR.

**Comment by manisandro** [comment] 2019-06-17 08:28
PR merged, thanks @elemoine!

**Closed by manisandro** 2019-06-17 08:28 UTC
