### ISSUE TITLE
Error message when changing a measurement line

### ISSUE THREAD

**Issue by stamogis** [qgis/qwc2-demo-app#348] opened 2022-04-26 13:11 UTC
When measuring a length with height profile and then moving a point of this measured line, an error message appears in the browser console:

`Uncaught TypeError: t.props.measurement.pickPositionCallback is not a function at MeasurementSupport.jsx:166`

However, I could not notice a negative effect in the program behavior.

**Comment by manisandro** [comment] 2022-04-26 13:28
I cannot reproduce this with the current master. Which git version are you using?

**Comment by stamogis** [comment] 2022-04-26 13:53
The error appears only when moving an existing point of the measurement line. When adding a new point to the measurement line, the error doesn't appear.

**Comment by manisandro** [comment] 2022-04-26 13:57
Ok now I got it! Fixed in https://github.com/qgis/qwc2/commit/0b8b3590edf765c7d7555f45d0cd4d09a1e1251b, thanks!

**Closed as completed by manisandro** 2022-04-26 13:57 UTC
