### ISSUE TITLE
Moving a layer up breaks the layertree

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/qwc2-demo-app#97] opened 2018-05-28 07:03 UTC
![problem](https://user-images.githubusercontent.com/3179646/40601569-6a1fce16-625e-11e8-9018-53963645e48f.gif)

Notice how moving the ``Ortfototo 2015`` creates another ``Topo`` group and if I want to move it another level up clicking on the Up arrow again doesn't do anything.

**Comment by manisandro** [comment] 2018-05-28 17:07
Can you provide a minimal qgis project with a layertree structure with which I can reproduce the issue? Along with a matching config.json/themesConfig.json. I am unable to reproduce the issues with any of my test themes.

**Comment by tudorbarascu** [comment] 2018-05-29 06:56
@manisandro I'll try (my projects are postgis based). I noticed however that the 4 test themes don't have groups, and the problem I'm seeing is when the layer goes into the upper group.

**Comment by manisandro** [comment] 2018-05-30 08:20
@tudorbarascu Could you send me a screenshot of the layertree structure in the QGIS project, and I'll try to replicate it? I suppose the structure is relevant, not the actual layer content.

**Comment by tudorbarascu** [comment] 2018-05-30 08:44
@manisandro Regarding the ``Uhm, the User project has groups?`` There's no group in any of the test themes, so I don't understand your statement. I notice that one difference between the test projects and mine is that I have  defined the ``project title`` in QGIS Desktop, named "Apă/Canal", and it appears in qwc2 as a root group. Also, I'm using QGIS 3 (master) Desktop and Server.

![image](https://user-images.githubusercontent.com/3179646/40709215-33851a04-63fe-11e8-8d7a-d4fe0f627f77.png)

**Comment by manisandro** [comment] 2018-05-30 10:05
I mean group in the layertree structure:

![screenshot_20180530_120312](https://user-images.githubusercontent.com/1298852/40714014-b6ae7b84-6401-11e8-88c5-dd3f78f40424.png)

**Comment by manisandro** [comment] 2018-05-30 12:14
@tudorbarascu Can you simplify your tree structure as much as possible, while still having the issue reproducible?

**Comment by tudorbarascu** [comment] 2018-05-30 13:39
Sure, will do it ASAP.
Regarding the test project that you're using and had the config in the demo projects, I see no groups in the output:
![image](https://user-images.githubusercontent.com/3179646/40723574-dcb14228-6427-11e8-9610-78b9633fb976.png)

Should I look somewhere else?

**Comment by manisandro** [comment] 2018-05-30 13:40
That's because currently the demo config has "flattenGroups" enabled in the layertree.

**Comment by tudorbarascu** [comment] 2018-05-30 19:05
Just tested again and narrowed down the curlprit.  The problem is only present when setting ``"expanded": false`` in ``themes.json`` for the group above the Ortofoto layer that I tested (the group name is Topo in my case).
I'm using that option for the very big groups as otherwise the usability from the user point of view is bad.. as there are too many layers when all the groups are expanded (big project)

**Comment by manisandro** [comment] 2018-06-07 12:16
As far as I can see, everything behaves as it is supposed to: If you move the layer upwards, it will split the group above to insert the moved layer inbetween, I.e.

    [group]
     [groupsublayer1]
     [groupsublayer2]
     [groupsublayer3]
    [movelayer]

Move up:

    [group]
     [groupsublayer1]
     [groupsublayer2]
    [movelayer]
    [group]
     [groupsublayer3]

Move up:

    [group]
     [groupsublayer1]
    [movelayer]
    [group]
     [groupsublayer2]
     [groupsublayer3]

etc.

The fact that the group is collapsed means that you don't actually see what's happening, which I suppose can be a bit confusing. In this example, if `[group]` were collapsed, you'd have to move `[movelayer]` upwards three times before it actually is above the entire group.

**Comment by manisandro** [comment] 2018-06-11 09:19
Closing, feel free to reopen if I missed something.

**Closed by manisandro** 2018-06-11 09:19 UTC
Labels: bug
