### ISSUE TITLE
Tutorial on qwc2-demo-app

### ISSUE THREAD

**Issue by d3netxer** [qgis/qwc2-demo-app#73] opened 2018-01-09 19:23 UTC
is there a tutorial on how to use the qwc2-demo-app?

I installed it and ran yarn start

Now how do I view it online? Is it supposed to see my qgis projects in my projects folder on my server?

**Comment by manisandro** [comment] 2018-01-09 22:21
The essential information is contained in the [README](https://github.com/qgis/qwc2-demo-app/blob/master/README.md).

> Now how do I view it online?

By default http://localhost:8081

> Is it supposed to see my qgis projects in my projects folder on my server?

No, you need to specify the themes in themeConfig.json according to the format documented in the README (just look at the sample themesConfig.json for a complete example). Themes basically correspond to QGIS projects, and the url in each theme entry is the url to the WMS served by QGIS Server.

**Comment by manisandro** [comment] 2018-01-11 16:08
Closing since it is pretty much a duplicate of #70.

**Closed by manisandro** 2018-01-11 16:08 UTC
