### ISSUE TITLE
yarn run prod gives error

### ISSUE THREAD

**Issue by huggla** [qgis/qwc2-demo-app#53] opened 2017-10-20 09:15 UTC
Row 7 in package-commands.sh: 
`NODE_ENV='production' webpack`

 Gives the following error: 

> ERROR in webpack-dev-server.js from UglifyJs Unexpected token: name (urlParts) [webpack-dev-server.js:8349,4]

I'm using latest Node and Yarn on Ubuntu 17.04

**Comment by manisandro** [comment] 2017-10-20 17:05
Hmm, I can't reproduce with `yarn-1.2.1` and `npm-5.4.2`. There are quite a few `urlParts` in the codebase, but AFAICS there is nothing obviously wrong...

**Comment by huggla** [comment] 2017-10-26 08:12
I found out that this only happens when I run `yarn upgrade` before `yarn run prod`.

**Comment by stephaschu** [comment] 2017-11-28 09:35
With the latest commit https://github.com/qgis/qwc2-demo-app/commit/a48bea10ed713ce993b364ed6478e9ac9075937b i'm facing the same issue as well, but didn't touch yarn upgrade at all. 
yarn-1.3.2
npm-5.5.1
nodejs-8.9.1

git clone --recursive https://github.com/qgis/qwc2-demo-app.git
cd qwc2-demo-app
yarn install
yarn run prod

> ERROR in webpack-dev-server.js from UglifyJs
> Unexpected token: name (urlParts) [webpack-dev-server.js:8643,4]

**Comment by manisandro** [comment] 2017-11-28 09:40
Hm indeed, investigating...

**Comment by manisandro** [comment] 2017-11-28 10:18
Should be fixed.

**Closed by manisandro** 2017-11-28 10:18 UTC

**Comment by stephaschu** [comment] 2017-11-28 10:21
working now, thanks!
