### ISSUE TITLE
map parameter not working in theme url

### ISSUE THREAD

**Issue by huggla** [qgis/qwc2-demo-app#19] opened 2017-03-20 11:19 UTC
Normally when having several .qgs files in one directory and want a wms from one of those you add the map=project.qgs parameter to the url. But if you, in themesConfig.json, give an url with the map parameter the theme ends up broken in qwc2.

**Comment by manisandro** [comment] 2017-03-22 16:39
Currently only the standard WMS URL format is supported (i.e. `http(s)://<host>/.../wms?SERVICE=WMS&VERSION=...&REQUEST=...`). You may need to define a RewriteRule for your webserver to rewrite the URLs appropriately.

**Comment by andreasneumann** [comment] 2017-04-18 11:09
See https://github.com/qgis/QGIS-Web-Client#5-url-rewriting

Can we close this issue or is it very important that the map parameter can be specified?

**Comment by huggla** [comment] 2017-04-20 10:52
I think it is important that qwc2 is Qgis Server compatible "out of the box", and the bug should remain open.  You could just set a low priority if you wish. We are using the suggested workaround for now.

**Comment by zoidable** [comment] 2018-07-29 13:19
hi,
+1 - also, I don't know how to implement the workaround with nginx, can you help?

**Comment by manisandro** [comment] 2018-07-29 21:14
If you search for "nginx rewrite rule" you get i.e. https://www.nginx.com/blog/creating-nginx-rewrite-rules/

**Comment by zoidable** [comment] 2018-07-30 05:07
Thanks, I figured that my problem was not caused by my rewrite rules but by trying to use https://github.com/3liz/docker-qgis-server. It works with rewrite and fcgi wrap now, but if the map parameter wouldn't be cut off, it'd probably also work with the server mentioned above :)

**Comment by manisandro** [comment] 2019-02-13 18:14
Map parameter is now preserved (see https://github.com/qgis/qwc2/commit/e713ef38bf068c3d66b06b98d1a09eb4eacc409c)

**Closed by manisandro** 2019-02-13 18:14 UTC
Labels: enhancement
